services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    restart: unless_stopped

    network_mode: host

#   env_file:
#     - .env

    environment:
      TZ: America/New_York # ${TZ}
      FTLCONF_webserver_api_password: 'password' # CHANGE this
      FTLCONF_dns_listeningMode: 'ALL'

    volumes:
      - ./data/pihole:/etc/pihole
      - ./data/dnsmasq:/etc/dnsmasq.d

    cap_add:
      - NET_ADMIN
